const fs=require('node:fs'),assert=require('node:assert/strict'),test=require('node:test'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,f);
const Module=require('node:module'),load=Module._load;
Module._load=function(id,...args){return id==='server-only'?{}:load.call(this,id,...args);};
const {analyseGemini,handleScan,ScanError}=require('../src/lib/ai/gemini-provider.ts');
Module._load=load;
const {scanInputSchema,parseWardrobe,demoWardrobe,reviewedWardrobe}=require('../src/lib/ai/wardrobe-schema.ts');
const photo='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jY1kAAAAASUVORK5CYII=';
const field=value=>({value,confidence:.9,evidence:'Visible label and garment details.'});
const suggestion=()=>({itemType:field('Denim Jeans'),visibleCondition:field('Good'),material:field('Cotton Blend Denim'),composition:{fibres:[{name:'Cotton',percent:98},{name:'Elastane',percent:2}],source:'care_label'},visibleDamage:[],reusablePanelsLikely:true});
const input={description:'',garmentPhoto:photo,careLabelPhoto:photo};
test('image-only, label-only and description-only scans accepted; empty input rejected',()=>{assert.ok(scanInputSchema.parse({description:'',garmentPhoto:photo}));assert.ok(scanInputSchema.parse({careLabelPhoto:photo}));assert.ok(scanInputSchema.parse({description:'jeans'}));assert.throws(()=>scanInputSchema.parse({description:' '}));});
test('label evidence populates suggestions, not verification',()=>{const s=parseWardrobe(suggestion(),input);assert.equal(s.material.value,'Cotton Blend Denim');assert.equal(s.composition.fibres[0].percent,98);assert.equal(s.itemType.value,'Denim Jeans');});
test('appearance cannot prove fibre composition even at high confidence',()=>{const s=parseWardrobe(suggestion(),{description:'',garmentPhoto:photo});assert.equal(s.material.value,'Unknown');assert.deepEqual(s.composition.fibres,[]);});
test('weak and unsupported materials stay Unknown; unsupported item discarded',()=>{const s=suggestion();s.material.value='Polyester';s.itemType.value='Sneakers';assert.equal(parseWardrobe(s,input).itemType.value,null);assert.equal(parseWardrobe(s,input).material.value,'Unknown');s.material=field('Cotton Denim');s.material.confidence=.4;assert.equal(parseWardrobe(s,input).material.value,'Unknown');});
test('malformed and impossible composition rejected',()=>{assert.throws(()=>parseWardrobe({},input));const s=suggestion();s.composition.fibres[0].percent=100;assert.throws(()=>parseWardrobe(s,input));});
for(const key of ['verified_kg','reward_amount','capacity','unlocked','material_allocation','verified_quality'])test(`Gemini cannot inject ${key}`,()=>{assert.throws(()=>parseWardrobe({...suggestion(),[key]:999},input));});
test('human corrections use allowlisted fields and unknown type requires selection',()=>{assert.deepEqual(reviewedWardrobe('Denim Jacket','Unknown','Repairable'),{type:'Denim Jacket',material:'Unknown',condition:'Repairable'});assert.throws(()=>reviewedWardrobe('','Cotton','Good'));});
test('Demo AI needs no key and never pretends to inspect photos',()=>{const s=demoWardrobe({description:'',garmentPhoto:photo});assert.equal(s.itemType.value,null);assert.equal(s.material.value,'Unknown');assert.equal(demoWardrobe({description:'damaged jeans'}).itemType.value,'Denim Jeans');});
test('Gemini official request carries labelled inline images and server header',async()=>{process.env.GEMINI_API_KEY='test-key';process.env.GEMINI_MODEL='test-model';try{const s=await analyseGemini(input,async(url,options)=>{assert.match(url,/generativelanguage.googleapis.com/);assert.equal(options.headers['x-goog-api-key'],'test-key');const b=JSON.parse(options.body);assert.equal(b.contents[0].parts.filter(p=>p.inlineData).length,2);assert.ok(b.generationConfig.responseJsonSchema);return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(suggestion())}]}}]});});assert.equal(s.material.value,'Cotton Blend Denim');}finally{delete process.env.GEMINI_API_KEY;delete process.env.GEMINI_MODEL;}});
test('quota, bad key/model, refusal, malformed output and network errors are actionable',async()=>{process.env.GEMINI_API_KEY='test';process.env.GEMINI_MODEL='test';try{for(const [status,message] of [[429,/quota or rate limit/],[401,/key/],[404,/model/]])await assert.rejects(analyseGemini(input,async()=>new Response('',{status})),message);await assert.rejects(analyseGemini(input,async()=>Response.json({promptFeedback:{blockReason:'SAFETY'}})),/could not complete/);await assert.rejects(analyseGemini(input,async()=>Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:'invalid'}]}}]})),/malformed/);await assert.rejects(analyseGemini(input,async()=>{throw Error('secret transport details');}),/connection failed/);}finally{delete process.env.GEMINI_API_KEY;delete process.env.GEMINI_MODEL;}});
test('missing config never silently falls back; bad image bytes rejected',async()=>{await assert.rejects(analyseGemini(input),/not configured/);await assert.rejects(analyseGemini({description:'',garmentPhoto:'data:image/png;base64,YWJj'}),/contents do not match/);});
test('timeout aborts the provider request and exposes no transport details',async(t)=>{
  process.env.GEMINI_API_KEY='test';process.env.GEMINI_MODEL='test';
  t.mock.timers.enable({apis:['setTimeout']});
  try{
    const pending=analyseGemini(input,async(_url,options)=>new Promise((_resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new Error('aborted')))));
    const check=assert.rejects(pending,/timed out/);t.mock.timers.tick(30001);await check;
  }finally{t.mock.timers.reset();delete process.env.GEMINI_API_KEY;delete process.env.GEMINI_MODEL;}
});
test('HTTP boundary rejects empty/oversized inputs and returns useful quota error',async()=>{const req=body=>new Request('http://localhost/api/wardrobe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal((await handleScan(req({description:''}))).status,400);assert.equal((await handleScan(req({description:'x'.repeat(5700001)}))).status,413);const response=await handleScan(req(input),async()=>{throw new ScanError('Gemini quota or rate limit reached. Retry later or switch to Demo AI.',429);});assert.equal(response.status,429);assert.match((await response.json()).error,/quota/);});
