import { Batch, ConceptId } from "../mock-data";
import { ConsumerItem } from "../return-engine";
import { Actor } from "./domain";
export type Requirement = {
  id: string;
  drop_id: string;
  component: string;
  material_type: string;
  minimum_kg: number;
  required_kg: number;
  maximum_kg: number;
  kg_per_unit: number;
  allowed_blend: boolean;
  accepted_grades: string[];
  allocated_kg: number;
  capacity: number;
};
export type StoredDrop = {
  id: string;
  code: string;
  name: string;
  brand_id: string;
  concept_id: string;
  batch_id: string | null;
  recipe_key: string;
  phase: string;
  state: string;
  preorder_threshold: number;
  selling_price: number;
  unit_cost: number;
  requirements: Requirement[];
  auxiliary: {
    id: string;
    component: string;
    unit: string;
    per_unit: number;
    mass_per_unit_kg: number;
    available: number;
    capacity: number;
    ready: boolean;
    required_quantity: number;
  }[];
  orders: number;
  votes: number;
  reservations: number;
  capacity: number;
  maximum_capacity: number;
  planned_units: number;
  allocated_kg: number;
  demand_ready: boolean;
  material_ready: boolean;
  eligible: boolean;
  my_order: boolean;
  my_preorder_status: string | null;
  my_vote: boolean;
  my_reservation: boolean;
  gross_sales: number;
};
export type StoredBatch = {
  id: string;
  code: string;
  brand_id: string;
  status: string;
  route: string | null;
  analysis: import("../circular-engine").CircularAnalysis | null;
  inputs: Batch;
  estimated_kg: number;
  verified_kg: number | null;
  allocated_kg: number;
  remaining_kg: number;
  source_id: string | null;
  used_by: { drop_code: string; kg: number }[];
};
export type StoredConcept = {
  id: string;
  batch_id: string | null;
  recipe_key: ConceptId | string;
  name: string;
  approved: boolean;
  reasoning: string;
  selling_price: number;
  unit_cost: number;
  input_kg: number;
  preorder_threshold: number;
  utilisation: number;
};
export type StoredItem = {
  id: string;
  user_id: string;
  item_type: ConsumerItem["type"];
  estimated_material_type: ConsumerItem["material"];
  estimated_condition: ConsumerItem["condition"];
  age_months: number;
  usage: ConsumerItem["usage"];
  estimated_recoverable_kg: number;
  recommendation: string;
};
export type StoredReturn = {
  id: string;
  consumer_item_id: string;
  target_drop_id: string;
  user_id: string;
  status: string;
  estimated_material_kg: number;
  verified_material_kg: number | null;
  verified_material_type: string | null;
  inspection_result: string | null;
  quality_grade: string;
  composition: string;
  colour_family: string;
  fabric_weight: string;
  panel_grade: string;
  contamination_status: string;
  point_name: string;
  return_by: string;
  source_id: string | null;
  allocated_kg: number;
  reward: number;
  reward_bonus: number;
  remaining_kg: number;
};
export type Source = {
  id: string;
  source_type: string;
  material_type: string;
  verified_kg: number;
  remaining_kg: number;
  batch_id: string | null;
  receipt_id: string | null;
  production_run_id: string | null;
  label: string;
  quality_grade: string;
  composition: string;
  colour_family: string;
  fabric_weight: string;
  panel_grade: string;
  contamination_status: string;
};
export type Production = {
  id: string;
  drop_id: string;
  confirmed_units: number;
  allocated_material_kg: number;
  estimated_total_cost: number;
  gross_committed_sales: number;
  status: string;
  residual_kg: number;
  consumed_kg: number;
};
export type Match = {
  dropId: string;
  dropCode: string;
  name: string;
  requirementId: string;
  compatible: boolean;
  compatibilityScore: number;
  reason: string;
  recoverableKg: number;
  neededKg: number;
  reward: { base: number; bonus: number; total: number };
};
export type Snapshot = {
  actor: Actor;
  workspaceName: string;
  workspaces: { id: string; name: string }[];
  users: Actor[];
  batches: StoredBatch[];
  concepts: StoredConcept[];
  drops: StoredDrop[];
  items: StoredItem[];
  returns: StoredReturn[];
  sources: Source[];
  production: Production[];
  massBalances: {
    production_run_id: string;
    allocated_kg: number;
    consumed_kg: number;
    process_scrap_kg: number;
    recoverable_residual_kg: number;
    non_recoverable_residual_kg: number;
  }[];
  exceptions: {
    id: string;
    production_run_id: string;
    reason: string;
    code: string;
  }[];
  releases: {
    id: string;
    allocation_id: string;
    quantity_kg: number;
    code: string;
  }[];
  allocations: {
    id: string;
    drop_id: string;
    source_id: string;
    quantity_kg: number;
    original_kg: number;
    code: string;
  }[];
  auxiliarySources: {
    id: string;
    component: string;
    unit: string;
    remaining_quantity: number;
  }[];
  points: { id: string; name: string; hours: string }[];
  rewards: {
    id: string;
    type: string;
    amount: number;
    reason: string;
    receipt_id: string | null;
    lifecycle: string;
    original_transaction_id: string | null;
    created_at: string;
  }[];
  balance: number;
  preorders: {
    id: string;
    drop_id: string;
    code: string;
    unit_price: number;
    status: string;
    payment_status: string;
  }[];
  contributions: {
    id: string;
    source_type: string;
    source_id: string;
    destination_type: string;
    destination_drop_id: string | null;
    drop_code: string | null;
    quantity_kg: number;
    released_kg: number;
    net_kg: number;
    created_at: string;
  }[];
  audit: { id: string; type: string; details: unknown; created_at: string }[];
  analytics: {
    preorders: number;
    reservations: number;
    reservationConversion: number;
    returns: number;
    acceptedReturns: number;
    returnRate: number;
    popularConcept: string;
    commonMaterial: string;
    averageMatch: number;
    routes: { route: string; count: number }[];
  };
};
