import {Sparkles} from 'lucide-react';
import {ConceptId,money} from '@/lib/mock-data';
import {Concept} from '@/lib/remix-engine';
import {calculateEconomics} from '@/lib/economics';
import {ProductImage,SectionTitle} from './ui';
export function ConceptsView({concepts,selected,onSelect,onLaunch,locked}:{concepts:Concept[];selected:ConceptId;onSelect:(id:ConceptId)=>void;onLaunch:()=>void;locked:boolean}){
 const active=concepts.find(c=>c.id===selected)!;
 return <><SectionTitle eyebrow="03 / CIRCULAR DESIGN ENGINE" title="Same denim. Three new directions." description="Material-led concepts calculated from your batch. Choose one direction for the demand test."/><div className="concept-grid">{concepts.map(c=>{const e=calculateEconomics(c,0);return <article className={`concept-card ${selected===c.id?'selected-concept':''}`} key={c.id}><div className="image-wrap"><ProductImage concept={c}/><span className="image-badge">{selected===c.id?'SELECTED CONCEPT':`${c.max} POSSIBLE UNITS`}</span></div><div className="concept-content"><h2>{c.name}</h2><p>{c.subtitle}</p><dl className="concept-details"><div><dt>Maximum quantity</dt><dd>{c.max} units</dd></div><div><dt>Est. production cost / unit</dt><dd>{money(c.cost)}</dd></div><div><dt>Suggested selling price</dt><dd>{money(c.price)}</dd></div><div><dt>Est. material utilisation</dt><dd>{c.utilisation}%</dd></div><div><dt>Difficulty</dt><dd>{c.difficulty}</dd></div><div><dt>Prototype order minimum</dt><dd>{c.threshold}</dd></div><div><dt>Maximum gross sales</dt><dd>{money(e.maximumGrossSales)}</dd></div><div><dt>Est. full-capacity production cost</dt><dd>{money(e.maximumProductionCost)}</dd></div></dl><div className="reason"><Sparkles size={16}/><p>{c.reason}</p></div><details className="why-route"><summary>Capacity & price assumptions</summary><p>{c.capacityExplanation}</p><p>Suggested price scales with the square root of original retail price / 69 and a material factor. Production cost scales with material, condition and small-batch effort. Utilisation is an estimated design yield, not proven waste diversion.</p></details><button className={selected===c.id?'primary full-button':'secondary full-button'} aria-pressed={selected===c.id} disabled={!c.feasible||(locked&&selected!==c.id)} onClick={()=>onSelect(c.id)}>{!c.feasible?'Below production minimum':selected===c.id?'Selected for this drop':`Select ${c.name}`}</button></div></article>;})}</div><div className="decision-bar"><div><h3>{active.feasible?`${active.name} selected. Let demand shape the next step.`:'Not enough material for the selected concept.'}</h3><p>Alternative uses of the same batch: capacities cannot be added together. Only the selected concept accepts pre-orders. {locked?'An order has been placed; reset or edit inventory to start another scenario.':''}</p></div><button className="primary" onClick={onLaunch} disabled={!active.feasible}>Launch consumer drop</button></div><p className="fine-print">Prototype estimates. Order minima are assumed maker batch requirements, not break-even calculations. Costs exclude setup, logistics, fees and returns; gross sales are not profit.</p></>;
}
