'use client';
import {useEffect,useRef,useState} from 'react';
import {Sparkles,CheckCircle2} from 'lucide-react';
import {Batch,materials,conditions} from '@/lib/mock-data';
import {AIMode,Extraction,Field,InventoryInput,InventoryReview,reviewFromExtraction,confirmInventory,confidenceLabel} from '@/lib/ai/inventory-analysis';
import {analyseInventory} from '@/lib/ai/client';
import {exampleDescription} from '@/lib/ai/mock-ai';
import {AIModeSelect} from './ai-mode';
export function InventoryAssistant({price,mode,connected,onMode,onConfirm}:{price:number;mode:AIMode;connected:boolean;onMode:(mode:AIMode)=>void;onConfirm:(batch:Batch)=>void}){
 const [open,setOpen]=useState(true),[input,setInput]=useState<InventoryInput>({description:exampleDescription,notes:'',csv:''});
 const [result,setResult]=useState<Extraction|null>(null),[review,setReview]=useState<InventoryReview|null>(null);
 const [edited,setEdited]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false);
 const request=useRef<AbortController|null>(null);
 useEffect(()=>()=>request.current?.abort(),[]);
 const changeInput=(next:InventoryInput)=>{request.current?.abort();setBusy(false);setInput(next);setResult(null);setReview(null);setError('');setConfirmed(false);};
 const extract=async()=>{
  if(![input.description,input.notes,input.csv,input.image].some(v=>v?.trim())){setError('Add a description, notes, a CSV row or an image.');return;}
  request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setError('');setResult(null);setReview(null);
  try{const data=await analyseInventory(mode,input,controller.signal);if(controller.signal.aborted)return;setResult(data);setReview(reviewFromExtraction(data,price));setEdited([]);}
  catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Analysis failed. Try Demo AI.');}
  finally{if(!controller.signal.aborted)setBusy(false);}
 };
 const edit=(field:keyof InventoryReview,value:string)=>{if(!review)return;setReview({...review,[field]:value});setEdited(old=>[...new Set([...old,field])]);};
 const confidence=(field:Field,key:keyof InventoryReview)=>edited.includes(key)?'Edited by you · confirm below':`${confidenceLabel(result?.confidence[field]??null)}${mode==='demo'?' · illustrative':''}`;
 return <section className="panel ai-inventory"><div className="ai-heading"><div><span className="eyebrow">OPTIONAL / AI INVENTORY ASSISTANT</span><h2>{confirmed?'Inventory reviewed by you':'Describe your stock.'}</h2><p>Add a description or inventory row, then review the suggested details before saving.</p></div><button className="secondary" onClick={()=>setOpen(!open)} aria-expanded={open}>{open?'Use manual form':confirmed?'Analyse another description':'Analyse Inventory'}</button></div>{open&&<>
 <div className="ai-input-grid"><div><label>Product description<textarea rows={3} maxLength={6000} value={input.description} disabled={busy} onChange={e=>changeInput({...input,description:e.target.value})}/></label><label>Inventory notes <span className="muted">optional</span><textarea rows={2} maxLength={6000} value={input.notes} disabled={busy} onChange={e=>changeInput({...input,notes:e.target.value})} placeholder="Defects, measurements, or anything that needs checking"/></label></div><div><label>CSV-like inventory row <span className="muted">optional</span><textarea rows={3} maxLength={6000} value={input.csv} disabled={busy} onChange={e=>changeInput({...input,csv:e.target.value})} placeholder={'product,quantity,material,condition\nDenim Jeans,180,Cotton Denim,Unsold / Minor Defects'}/></label><label>Product image <span className="muted">optional · up to 2 MB</span><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file){changeInput({...input,image:undefined});return;}if(file.size>2*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Choose a PNG, JPEG or WebP image up to 2 MB.');e.target.value='';return;}try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});changeInput({...input,image:data});}catch{setError('Could not read this image.');}}}/></label>{input.image&&<div className="image-preview"><img src={input.image} alt="Inventory reference uploaded for review"/><button className="text-button" onClick={()=>changeInput({...input,image:undefined})}>Remove image</button></div>}</div></div>
 <div className="ai-toolbar"><AIModeSelect mode={mode} connected={connected} disabled={busy} onChange={m=>{onMode(m);setResult(null);setReview(null);setError('');}}/><button className="primary" onClick={extract} disabled={busy}><Sparkles size={16}/>{busy?'Analysing…':'Analyse Inventory'}</button></div><p className="fine-print">{mode==='demo'?'Demo AI uses deterministic text rules and example suggestions. Images are shown for human reference only; no model or image analysis runs.':'Connected AI sends this description, notes, CSV and optional image to OpenAI when you analyse. Suggestions can be wrong; review before applying.'} Confidence labels are approximate, not measured probabilities.</p>
 {error&&<p className="ai-error" role="alert">{error}</p>}
 {result&&review&&<form className="ai-review" onSubmit={e=>{e.preventDefault();try{const batch=confirmInventory(review);onConfirm(batch);setConfirmed(true);setOpen(false);setError('');}catch(e){setError(e instanceof Error?e.message:'Review the fields.');}}}><div className="ai-heading"><div><span className="eyebrow">{mode==='demo'?'DEMO AI SUGGESTIONS':'CONNECTED AI SUGGESTIONS'}</span><h3>Review before you confirm.</h3><p>Unknown details stay blank. Check and correct the fields before saving.</p></div></div><div className="form-grid">
 <label>Product type<input required maxLength={80} value={review.productType} onChange={e=>edit('productType',e.target.value)}/><small>{confidence('productType','productType')}</small></label>
 <label>Extracted quantity<input required type="number" min={1} max={100000} step={1} value={review.quantity} onChange={e=>edit('quantity',e.target.value)}/><small>{confidence('quantity','quantity')}</small></label>
 <label>Extracted material<select required value={review.material} onChange={e=>edit('material',e.target.value)}><option value="">Needs your confirmation</option>{materials.map(m=><option key={m}>{m}</option>)}</select><small>{confidence('material','material')}</small></label>
 <label>Extracted condition<select required value={review.condition} onChange={e=>edit('condition',e.target.value)}><option value="">Needs your confirmation</option>{conditions.map(c=><option key={c}>{c}</option>)}</select><small>{confidence('condition','condition')}</small></label>
 <label>Reusable weight (kg)<input type="number" min={0} max={100000} step="0.1" value={review.weight} onChange={e=>edit('weight',e.target.value)} placeholder="Unknown · use a rule-based estimate"/><small>{confidence('estimatedReusableMaterial','weight')}</small></label>
 <label>Confirm original retail price (SGD)<input required type="number" min={1} max={100000} step="0.01" value={review.price} onChange={e=>edit('price',e.target.value)}/><small>From the manual form · not decided by AI</small></label></div>
 <details className="why-route"><summary>Uncertainty & assumptions</summary><ul>{result.warnings.map(w=><li key={w}>{w}</li>)}<li>Classification does not verify fabric composition or garment condition.</li><li>Unknown material weight will be estimated by the deterministic engine.</li></ul></details><button className="primary" type="submit"><CheckCircle2 size={16}/> Confirm inventory & calculate routes</button></form>}
 </>}</section>;
}
