'use client';
import {useEffect,useRef,useState} from 'react';
import {CheckCircle2,XCircle,Sparkles} from 'lucide-react';
import {Batch} from '@/lib/mock-data';
import {AIMode} from '@/lib/ai/inventory-analysis';
import {Suggestion,VerifiedOpportunity,verifyOpportunities} from '@/lib/ai/concept-generator';
import {generateConcepts} from '@/lib/ai/client';
import {AIModeSelect} from './ai-mode';
export type OpportunityResult={suggestions:Suggestion[];mode:AIMode;target:string;checks?:VerifiedOpportunity[]};
export function OpportunityAssistant({batch,mode,connected,onMode,result,onResult,locked}:{batch:Batch;mode:AIMode;connected:boolean;onMode:(m:AIMode)=>void;result:OpportunityResult|null;onResult:(r:OpportunityResult|null)=>void;locked:boolean}){
 const [target,setTarget]=useState('Daily commuting'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const request=useRef<AbortController|null>(null);useEffect(()=>()=>request.current?.abort(),[]);
 const generate=async()=>{request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setError('');onResult(null);try{const suggestions=await generateConcepts(mode,batch,target,controller.signal);if(!controller.signal.aborted)onResult({suggestions,mode,target});}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Generation failed. Try Demo AI.');}finally{if(!controller.signal.aborted)setBusy(false);}};
 const verified=result?(result.checks??verifyOpportunities(batch,result.suggestions)):[];
 return <section className="panel opportunity-panel"><div className="ai-heading"><div><span className="eyebrow">AI DESIGN SUGGESTIONS</span><h2>Generate Remix Opportunities</h2><p>Suggest designs for this batch, then check them against registered recipes and available material.</p></div></div><div className="ai-toolbar"><label className="ai-target">Who is this for?<input maxLength={120} value={target} disabled={busy||locked} onChange={e=>{setTarget(e.target.value);onResult(null);}}/></label><AIModeSelect mode={mode} connected={connected} disabled={busy||locked} onChange={m=>{onMode(m);onResult(null);}}/><button className="primary" onClick={generate} disabled={busy||locked||!target.trim()}><Sparkles size={16}/>{busy?'Generating design ideas…':result?'Regenerate opportunities':'Generate Remix Opportunities'}</button></div><p className="fine-print">{mode==='demo'?'Demo AI · curated ideas, no external API.':'Connected AI · sends confirmed inventory attributes and audience to OpenAI.'} Economic checks use known unit cost and maker minimum; they do not certify profit.</p>{error&&<p role="alert" className="ai-error">{error}</p>}
 {result&&<><div className="opportunity-summary" role="status"><strong>{verified.filter(v=>v.approved).length} passed deterministic feasibility</strong><span>{result.mode==='demo'?'Demo AI proposals':'Connected AI proposals'} · {verified.filter(v=>!v.approved).length} not currently feasible</span></div><div className="opportunity-grid">{verified.map(v=><details key={v.suggestion.name} className={`opportunity ${v.approved?'approved':'rejected'}`}><summary><span><strong>{v.suggestion.name}</strong><small>{v.approved?'FEASIBLE PROPOSAL · APPROVAL REQUIRED':'NOT CURRENTLY FEASIBLE'}</small></span>{v.approved?<CheckCircle2 size={18}/>:<XCircle size={18}/>}</summary><p><strong>Why AI suggested this</strong><br/>{v.suggestion.reason}</p><ol className="feasibility-steps">{v.checks.map(check=><li key={check.label}><span>{check.passed?<CheckCircle2 size={15}/>:<XCircle size={15}/>}<strong>{check.label}</strong></span><p>{check.detail}</p></li>)}</ol></details>)}</div><p className="fine-print">AI ideas are proposals, not finished products. Only supported recipes can proceed, after brand and simulated maker approval.</p></>}
 </section>;
}
