'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,CheckCircle2,Scissors,Sparkles} from 'lucide-react';
import {Batch,money} from '@/lib/mock-data';
import {ConsumerItem,defaultItem,itemTypes,itemMaterials,itemConditions,itemUsages,confirmItem,recommendAction,collectionPoints,returnDeadline} from '@/lib/return-engine';
import {matchMaterial,loopRecipe} from '@/lib/material-match-engine';
import {demandBonus,materialShortage} from '@/lib/commerce-engine';
import {calculateRewards} from '@/lib/rewards-engine';
import {LoopState,loopSummary,reserveItem,confirmReceipt,placeLoopOrder,completeLoop,demandIntelligence} from '@/lib/loop-engine';
import {stylingSuggestions} from '@/lib/ai/styling-suggestions';
import {AIMode} from '@/lib/ai/inventory-analysis';
import {WardrobeScanner} from './wardrobe-scanner';
import {Progress,SectionTitle,ProductImage} from './ui';
import {calculateConcepts} from '@/lib/remix-engine';
type Props={state:LoopState;onChange:(update:(old:LoopState)=>LoopState)=>void;batch:Batch;mode:AIMode;connected:boolean;onMode:(mode:AIMode)=>void;brandLocked:boolean;availableStockKg?:number;onShop?:()=>void};
export function RemixLoop({state,onChange,batch,mode,connected,onMode,brandLocked,availableStockKg=0,onShop}:Props){
 const [item,setItem]=useState<ConsumerItem>(state.reservation?.item??defaultItem),[reviewed,setReviewed]=useState(false),[location,setLocation]=useState<string>(collectionPoints[0]);
 const [error,setError]=useState('');
 const impactRef=useRef<HTMLDivElement>(null),request=useRef(0);
 const result=loopSummary(state.pool,state.orders,state.completed),match=matchMaterial(item,state.pool,state.orders),legacyReward=calculateRewards(item,state.pool,state.orders),action=recommendAction(item),reservation=state.reservation;
 const bonus=demandBonus(legacyReward.base,materialShortage(result.requiredKg,result.kg,availableStockKg),state.orders,0,0,10000);
 const reward={...legacyReward,bonus,total:legacyReward.base+bonus,discountPercent:legacyReward.base?10:0};
 const locked=!!reservation||brandLocked;
 useEffect(()=>{if(result.unlocked){impactRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});impactRef.current?.focus({preventScroll:true});}},[result.unlocked]);
 const update=(patch:Partial<ConsumerItem>)=>{setItem(old=>({...old,...patch}));setReviewed(false);};

 const order=()=>onShop?onShop():onChange(placeLoopOrder);
 return <><SectionTitle eyebrow="REMIX LOOP / DEMAND-DRIVEN MATERIAL RECOVERY" title="Your next chapter starts here." description="Demand tells us what materials are needed. Recovered materials determine what can be produced."/>
 <div className="loop-steps" aria-label="Circular consumer loop">{['Wear','Return','Match','Unlock','Remix'].map((s,i)=><span key={s}><small>0{i+1}</small>{s}{i<4&&<ArrowRight size={16}/>}</span>)}</div>
 {brandLocked&&<p className="callout">The brand demo already has an order commitment. Reset the demo to allocate this batch to Remix Loop instead. The same material cannot fund two drops.</p>}
 <div className="loop-layout"><section className="panel loop-panel"><span className="eyebrow">01 / YOUR WARDROBE</span><h2>Scan an item</h2><p>Start with what you own. Keeping it in use comes first.</p>
 <WardrobeScanner staticOnly disabled={locked} onApply={update}/>
 <form onSubmit={e=>{e.preventDefault();try{confirmItem(item);setReviewed(true);setError('');}catch(e){setError(String(e));}}}><fieldset disabled={locked} className="loop-fields"><div className="form-grid"><label>Clothing type<select value={item.type} onChange={e=>update({type:e.target.value as ConsumerItem['type']})}>{itemTypes.map(v=><option key={v}>{v}</option>)}</select></label><label>Item material<select value={item.material} onChange={e=>update({material:e.target.value as ConsumerItem['material']})}>{itemMaterials.map(v=><option key={v}>{v}</option>)}</select></label><label>Item condition<select value={item.condition} onChange={e=>update({condition:e.target.value as ConsumerItem['condition']})}>{itemConditions.map(v=><option key={v}>{v}</option>)}</select></label><label>Current usage<select value={item.usage} onChange={e=>update({usage:e.target.value as ConsumerItem['usage']})}>{itemUsages.map(v=><option key={v}>{v}</option>)}</select></label><label>Age in months<input type="number" min="0" max="1200" required value={item.ageMonths} onChange={e=>update({ageMonths:Math.max(0,Math.min(1200,Number(e.target.value)||0))})}/></label></div><p className="fine-print">Review and confirm. Age is context, never a reason to dispose of wearable clothing.</p><button className="primary" type="submit">Confirm item <ArrowRight size={16}/></button></fieldset></form>
 {error&&<p role="alert">{error}</p>}
 {(reviewed||reservation)&&<div className="loop-recommendation" role="status"><span className="eyebrow">CIRCULAR ACTION RECOMMENDATION</span><h3>{action.action}</h3><p>{action.reason}</p><details><summary>Why this action?</summary><p>Keep & restyle → repair → resell / donate → return for Remix → recycle. Usable, unwanted clothing goes to another wearer. Material recovery is for items no longer wearable; unknown material requires review.</p></details>
 {action.action==='KEEP & RESTYLE'&&<><h3>3 ways to wear this again</h3><ol>{stylingSuggestions(item).map(s=><li key={s}>{s}</li>)}</ol><p><em>“The most sustainable item may be the one you keep wearing.”</em></p><small>Mock styling suggestions · use what you already own.</small></>}
 {action.action==='REPAIR'&&<p>Try a small stitching or fastening repair, then reassess wearability. No return incentive is offered.</p>}
 {action.action==='RESELL / DONATE'&&<p>Offer it to another wearer or a donation organisation that accepts this condition. No recovery incentive is offered for a wearable item.</p>}
 {action.action==='RETURN FOR REMIX'&&<><h3>{match.materialMatch==='high'?'High Material Match':'No active material match'}</h3><p>{match.materialMatch==='high'?'Cotton Denim · deterministic compatibility with DROP #024.':'This recipe requires Cotton Denim. Keep this material separate; no matching return reward is offered.'}</p><p>Estimated recoverable material: <strong>{match.estimatedRecoverableKg.toFixed(1)} kg</strong>. Rule-based estimate, subject to inspection.</p>{!reservation&&match.eligible&&<><p>Your inspected item can supply this batch. A bonus applies only when available compatible stock cannot cover its planned need.</p><div className="reward-lines"><span>Standard return reward <b>{reward.base} credits</b></span><span>Current Denim Material Bonus <b>+{reward.bonus} credits</b></span><strong>Total: {reward.total} credits</strong><small>{reward.discountPercent}% return discount after acceptance. Apply it with credits at the shop checkout.</small></div><label>Collection point<select value={location} onChange={e=>setLocation(e.target.value)}>{collectionPoints.map(p=><option key={p}>{p}</option>)}</select></label><p>11:00–19:00 · Return by {returnDeadline()}</p><p className="fine-print">Mock locations; no geolocation or real reservation. Credits are awarded only after simulated receipt.</p><button className="primary" disabled={brandLocked} onClick={()=>onChange(old=>reserveItem(old,item,location))}>Return for Remix · reserve collection</button></>}{!reservation&&!match.eligible&&<p>{match.materialStillNeededKg===0?'This material target is full. No additional return is requested.':'No compatible active material need. No return reservation or bonus.'}</p>}</>}
 </div>}
 {reservation&&<div className="loop-receipt" role="status"><span className="eyebrow">RETURN {reservation.id} · {reservation.status.toUpperCase()}</span><h3>{reservation.status==='Reserved'?'Your return is reserved.':'Your material is in the loop.'}</h3><p>{reservation.location} · 11:00–19:00 · by {reservation.returnBy}</p>{reservation.status==='Reserved'?<><p>Reservation adds 0 kg. A collection inspection must confirm the material before allocation.</p><button className="primary" disabled={brandLocked} onClick={()=>onChange(confirmReceipt)}>Simulate collection & verify +{reservation.estimatedKg.toFixed(1)} kg</button><button className="text-button" onClick={()=>onChange(old=>({...old,reservation:null}))}>Cancel reservation</button></>:<><p>Your returned material contributed {reservation.allocatedKg.toFixed(1)} kg to this Remix batch. Individual garment traceability is not available.</p>{reservation.estimatedKg>reservation.allocatedKg&&<p>{(reservation.estimatedKg-reservation.allocatedKg).toFixed(1)} kg of this return remains outside the drop allocation, awaiting another route.</p>}<strong>+{reservation.credits} circular credits · {reservation.discountPercent}% future preorder discount · Early access</strong><p className="fine-print">Simulated benefits. Apply eligible discounts and credits at the shop checkout; no real voucher is issued.</p></>}</div>}
 </section>
 <aside className="panel loop-panel loop-drop"><span className="eyebrow">ACTIVE DROP / 024</span><div className="loop-product"><ProductImage concept={calculateConcepts(batch)[0]}/><span>Illustrative bag concept · registered prototype recipe</span></div><h2>Denim Utility Bag</h2><p>Everyday function. Recovered denim. {money(loopRecipe.price)}</p><div className="loop-readiness" aria-live="polite"><div><strong>Demand <span>{state.orders} / 42</span></strong><Progress value={state.orders} max={42} label="Loop confirmed buyers"/><small>{result.demandReady?'DEMAND READY ✓':'1 buyer still needed'}</small></div><div><strong>Recovered material <span>{result.kg.toFixed(1)} / {result.requiredKg} kg</span></strong><Progress value={result.kg} max={result.requiredKg} label="Loop recovered material"/><small>{result.materialReady?'MATERIAL READY ✓':`${Math.max(0,result.requiredKg-result.kg).toFixed(1)} kg still needed`}</small></div></div><h3>{result.unlocked?'DROP UNLOCKED':result.demandReady?'DEMAND READY · MATERIAL STILL NEEDED':result.materialReady?'MATERIAL READY · DEMAND STILL NEEDED':'Both the material and the demand matter.'}</h3><p>{money(result.grossSales)} committed gross sales · simulated, not profit</p><button className="primary full-button" onClick={order} disabled={brandLocked||state.ordered||state.orders>=loopRecipe.maximumUnits}>{state.ordered?'Your pre-order is confirmed':'Demo: add the 42nd pre-order · SGD 49'}</button><p className="fine-print">No payment. Production requires at least 42 buyers and inspected material for the planned {result.plannedUnits} units.</p><div className="scarcity loop-scarcity"><Scissors size={20}/><div><span className="eyebrow">Waste-Defined Scarcity</span><h3>Maximum production: {loopRecipe.maximumUnits} units</h3><p>This limit comes from available recovered material, not artificial scarcity. Current verified material supports {result.capacity} units. The unlock requirement follows the planned batch, not the maximum.</p></div></div><details><summary>Material ledger & recipe assumptions</summary><p>Utility Bag: 1 kg of screened input per unit, including cutting allowance. Prototype assumption, distinct from the existing Tote recipe.</p>{state.pool.map(p=><p key={p.id}>{p.source==='brand_surplus'?'Brand surplus':'Consumer returns'} · {p.sourceId}: {p.kg.toFixed(1)} kg</p>)}<p>Sources stay separate. Drop 017 and Drop 024 are alternative allocations of D102, not simultaneous claims on its material.</p></details></aside></div>
 {result.unlocked&&<div id="loop-impact" ref={impactRef} tabIndex={-1} className="loop-impact"><div className="impact-hero" role="status"><CheckCircle2 size={40}/><div><span className="eyebrow">DEMAND READY ✓ / MATERIAL READY ✓</span><h2>DROP UNLOCKED</h2><p>{reservation?.status==='Received'?'You helped unlock Drop #024.':'The community helped unlock Drop #024.'} Only confirmed orders proceed to production.</p></div></div><div className="impact-grid">{[[state.orders,'confirmed buyers'],[`${result.kg} kg`,'recovered material · simulated'],[loopRecipe.maximumUnits,'waste-defined maximum production'],[money(result.grossSales),'committed gross sales'],[0,'speculative units produced']].map(([v,label])=><div className="metric" key={label}><strong>{v}</strong><h3>{label}</h3></div>)}</div>{!state.completed&&<button className="secondary" onClick={()=>onChange(completeLoop)}>Simulate making the {state.orders} confirmed orders</button>}{state.completed&&<div className="callout"><div><strong>DROP #024 COMPLETED · SIMULATED</strong><p>{result.communityReturns} community returns · {result.kg} kg recovered material · {result.produced} products produced · {state.orders} buyers confirmed before production · 0 speculative units.</p><p>{result.residualKg} kg unallocated screened input retained for a future batch. This is not a claim of verified onward recycling. Recipe allowance includes cutting residuals; actual recovered outputs need weighing.</p></div></div>}<p className="fine-print">All material and production figures are prototype estimates or simulations. No verified diversion or CO₂ savings are claimed.</p></div>}
 <DemandIntelligence state={state}/><div className="manifesto"><span className="eyebrow">REMIX LOOP</span><h2>Turn demand into recovery,<br/><span>and recovery into the next drop.</span></h2><p>AI interprets. Rules verify. Consumers validate.</p></div></>;
}
export function DemandIntelligence({state}:{state:LoopState}){const d=demandIntelligence(state.pool,state.orders);return <details className="architecture loop-intelligence"><summary>Brand demand intelligence · DROP #024</summary><div className="architecture-flow"><div><strong>Utility Bag: {d.demand}</strong><span>{state.orders} simulated preorders</span></div><div><strong>Design preferences</strong><span>No observed preference records in this static demo.</span></div><div><strong>{d.availableKg.toFixed(1)} kg compatible denim</strong><span>Capacity: {d.capacity} units</span></div></div><p><strong>{state.completed?'Completed batch':'Suggested batch'}: {d.nextBatch} units.</strong> min(confirmed orders, material capacity). {state.completed?'This is the completed batch record; it is not a new allocation.':'Release only after both thresholds are met; no speculative extras.'} Preferences inform design, never inflate orders or capacity.</p></details>;}
