import {Layers3} from 'lucide-react';
import {Batch,money} from '@/lib/mock-data';
import {CircularAnalysis} from '@/lib/circular-engine';
import {materialEstimate} from '@/lib/remix-engine';
import {Progress,SectionTitle} from './ui';
export function RouteAnalysis({batch,analysis,selected,onSelect,onEdit,onExplore}:{batch:Batch;analysis:CircularAnalysis;selected:string;onSelect:(route:string)=>void;onEdit:()=>void;onExplore:()=>void}){
 const stock=materialEstimate(batch);
 return <><SectionTitle eyebrow="02 / CIRCULAR ROUTE ENGINE" title="Remix is a choice. Not a default." description={`Compare four pathways for ${batch.quantity} ${batch.product.toLowerCase()}. Preserve value before creating something new.`}/>
 <div className="callout"><Layers3 size={20}/><span><strong>Prototype decision estimate · {stock.availableKg.toFixed(1)} kg available</strong><br/>Calculated from this batch’s quantity, price, material and condition. {stock.capped?'Material is capped by the estimated per-item weight.':''}</span><button className="text-button" onClick={onEdit}>Edit batch</button></div>
 <div className="route-grid">{analysis.routes.map((r,i)=><article key={r.name} className={`route-card ${selected===r.name?'selected':''}`}><div className="route-top"><span>0{i+1}</span>{analysis.recommendation===r.name&&<span className="blue-tag">RECOMMENDED</span>}</div><h2>{r.name}</h2><p>{r.description}</p><strong className="route-value">{money(r.value)}</strong><span className="muted">Estimated Value Recovery · gross</span><dl><div><dt>Waste Avoidance (est.)</dt><dd>{r.waste}%</dd></div><div><dt>Processing Effort</dt><dd>{r.processing}</dd></div><div><dt>Risk</dt><dd>{r.risk}</dd></div></dl><div className="score"><span>Circular Score</span><strong>{r.score}<small> / 100</small></strong></div><Progress value={r.score} max={100} label={`${r.name} circular score`}/>
 <details className="why-route"><summary>Why this route?</summary><ul>{r.explanation.map(e=><li key={e}>{e}</li>)}</ul><div className="factor-list">{r.factors.map(f=><div key={f.label}><span>{f.label}</span><strong>{f.rating.toFixed(1)} × {Math.round(f.weight*100)}% = {f.points.toFixed(2)}</strong></div>)}</div><p>Weighted points summed, then rounded to {r.score}. Value is normalised against the highest gross estimate. Waste avoidance and utilisation are scenario assumptions, not measured diversion.</p>{r.name==='Recycle'&&<p>Fallback gate: considered only if the other routes are not viable, regardless of score.</p>}</details>
 <button className={selected===r.name?'primary full-button':'secondary full-button'} onClick={()=>onSelect(r.name)} aria-pressed={selected===r.name}>{selected===r.name?'Selected':`Select ${r.name}`}</button></article>)}</div>
 <div className="decision-bar"><div><span className="eyebrow">RECOMMENDED: {analysis.recommendation??'NO VIABLE ROUTE'}</span><h3>{selected==='Remix'?'Test demand before committing this material.':`${selected}: preserve the value already here.`}</h3><p>{selected==='Remix'?'Explore alternative designs; select one concept for this batch’s pre-order test.':'This route needs no Remix production. You can still inspect remaking as an alternative.'}</p></div><button className="primary" onClick={onExplore}>{selected==='Remix'?'Explore Remix concepts':'Compare Remix alternative'}</button></div><p className="fine-print">Prototype decision estimate. The highest-scoring viable higher-value route wins; recycling is the fallback. Weights: value 30%, waste avoidance 20%, utilisation 15%, processing ease 10%, lower risk 10%, demand 15%. Financial estimates are gross sales, not profit. No scientifically validated environmental claim.</p></>;
}
